### PR TITLE
Rework implementation of appender statistics

### PR DESCRIPTION
**Pull request by yskopets**

### CODE REVIEW

**Comment by vy** [comment]
@yskopets, I liked the idea of exposing statistics model in `RedisAppender`, though I still think we should keep JMX integration in. It was serving a certain purpose, which I personally found handy. What do you think? Why did you ditched off the JMX part?

**Comment by yskopets** [comment]
@vy Ah, sorry!

For a use case that I'm working on we only need statistics collected from inside `RedisAppender`;  `JMX` integration by itself is not really a requirement.

As far as I can see, `log4j2` doesn't provide enough support for custom `JMX` beans in its lifecycle model.

So, I decided to settle for something that is just enough.

Of course, I can go back and apply my changes together with `JMX` rather than instead.

**Comment by vy** [comment]
@yskopets, I have added your changes (with slight modifications) while still keeping the JMX in. Would you mind checking it, please? So I can cut a release for this.

**Comment by yskopets** [comment]
Hi!

**Pull request closed without merging**
